/** @type {import('orval').Config} */
const config = {
  api: {
    input: {
      target: process.env.OPENAPI_SCHEMA_PATH,
    },
    output: {
      target: 'src/lib/api/generated/client.ts',
      schemas: 'src/lib/api/generated/models',
      mode: 'split',
      client: 'fetch',
      httpClient: 'fetch',
      clean: true,
      headers: true,
      baseUrl: {
        runtime: 'apiBaseUrl',
        imports: [{ name: 'apiBaseUrl', importPath: '../../../config/public-env' }],
      },
      override: {
        header: () => [
          '/* generated by Orval; do not edit. Regenerate with pnpm api:generate. */',
        ],
      },
    },
  },
};

export default config;
