import type { AiResultView, AiTaskView, ClarificationModeValue, CreateConfirmationRoundInput, CreateImplementationPlanInput, CreateProjectInput, CreatePrdInput, DecidePrdReviewInput, DeriveVersionInput, DesignReviewView, FrontendApi, ImplementationPlanView, PrdVersionView, PrdView, ProjectOverviewView, ProjectSummaryView, RequirementAssessmentView, RequirementBaselineView, RequirementContentView, RequirementView, SaveImplementationPlanVersionInput, SavePrdVersionInput, Scenario, SessionView, SubmitPrdReviewInput, UpdateConfirmationRoundDraftInput, VersionView } from "./ports";
import { capabilitiesForRoles, PortError } from "./ports";

export const MOCK_ADAPTER_NOTICE = "Sprint 1 first-wave mock: replace only after the frozen OpenAPI client is generated.";
const projects: ProjectSummaryView[] = [
  { id: "atlas", name: "Atlas 产品验证", goal: "验证核心需求并形成可审计版本", workingVersionId: "atlas-v2", workingVersionNo: "V2", projectVersion: 2, stage: "需求澄清", updatedAt: "2026-07-29T09:30:00Z" },
  { id: "nova", name: "Nova 工作台", goal: "整理项目上下文", workingVersionId: "nova-v1", workingVersionNo: "V1", projectVersion: 1, stage: "项目初始化", updatedAt: "2026-07-28T10:00:00Z" },
];
const versions: VersionView[] = [
  { id: "atlas-v2", number: "V2", source: "atlas-v1", reason: "补充目标用户约束", createdAt: "2026-07-29T09:30:00Z", isWorking: true },
  { id: "atlas-v1", number: "V1", source: null, reason: "创建项目", createdAt: "2026-07-28T09:00:00Z", isWorking: false },
];
const session: SessionView = { user: { id: "user-1", displayName: "林岚", email: "linlan@example.com" }, expiresAt: "2026-07-29T18:00:00Z" };
const wait = async () => Promise.resolve();
const fail = (scenario?: Scenario) => { if (scenario === "forbidden") throw new PortError("FORBIDDEN", "你没有执行此操作的权限。"); if (scenario === "conflict") throw new PortError("CONFLICT", "工作版本已被其他成员更新，请加载最新状态。"); if (scenario === "failure") throw new PortError("FAILED", "请求未完成，请保留当前内容后重试。"); };
const overview = (projectId: string, viewedVersionId = "atlas-v2"): ProjectOverviewView => { const version = versions.find((item) => item.id === viewedVersionId) ?? versions[0]; const roles = ["owner"] as const; return { ...projects[0], id: projectId, roles: [...roles], capabilities: capabilitiesForRoles([...roles]), viewedVersionId: version.id, viewedVersionNo: version.number, isHistory: !version.isWorking, canEdit: version.isWorking, blocker: "目标用户证据尚待补充" }; };

const dimensions = ["goal", "users_and_roles", "usage_scenarios", "functional_scope", "business_rules", "exception_cases", "permission_requirements", "acceptance_criteria"] as const;
const emptyBaseline = (): RequirementBaselineView => ({ assumptions: [], unresolvedItems: [], dimensions: Object.fromEntries(dimensions.map((key) => [key, { confirmedFacts: [], sourceRefs: [], deferredItems: [], notApplicableItems: [] }])) as unknown as RequirementBaselineView["dimensions"] });
const sourceRef = { sourceId: "manual-input", sourceVersionId: null, sourceType: "manual", label: "手工输入", contentHash: "0".repeat(64) };
const assessmentDimension = (status: "complete" | "partial" | "missing") => ({ status, missingItems: status === "complete" ? [] : ["需要用户补充"], reasons: [status === "complete" ? "原始输入已提供明确事实" : "原始输入中的证据不足"], sourceRefs: [sourceRef] });
const mockAssessment = (): RequirementAssessmentView => ({ aiResultId: "mock-assessment", assessmentVersion: "0.2.0", complexityBand: "medium", reasons: ["需要补充目标、角色与验收边界"], missingItems: ["目标量化标准", "异常边界"], dimensions: { goal: assessmentDimension("partial"), users_and_roles: assessmentDimension("partial"), usage_scenarios: assessmentDimension("partial"), functional_scope: assessmentDimension("complete"), business_rules: assessmentDimension("missing"), exception_cases: assessmentDimension("missing"), permission_requirements: assessmentDimension("partial"), acceptance_criteria: assessmentDimension("missing") }, missingDimensions: ["business_rules", "exception_cases", "acceptance_criteria"], recommendedMode: "standard", sourceRefs: [sourceRef] });
const content = (mode: ClarificationModeValue = "auto", rawInput = "待补充的原始需求"): RequirementContentView => ({ rawInput, rawInputRef: sourceRef, clarification: { mode, continueDeepConfirmed: false, assessmentRef: null, assessmentSummary: null, assessment: null, rounds: [], finishReason: null }, baseline: emptyBaseline() });
let mockRequirement: RequirementView = { requirement: { id: "req-atlas-1", title: "支持团队需求澄清", projectVersionId: "atlas-v2", status: "draft", sourceType: "manual", priority: "normal", currentVersionId: "req-v1", effectiveVersionId: null, version: 1, updatedAt: "2026-08-08T00:00:00Z" }, currentVersion: { id: "req-v1", requirementId: "req-atlas-1", versionNo: "V1", contentHash: "1".repeat(64), contentFormat: "application/json", content: content(), confirmationStatus: "draft", isEffective: false, sourceVersionId: null, createdFromAiResultId: null, unresolvedCount: 0, riskAcceptances: [] }, effectiveVersion: null, canEdit: true, allowedActions: ["edit", "revise", "confirm", "set_clarification_mode"] };
let taskCounter = 0;
const mockTasks = new Map<string, AiTaskView>();
const mockResults = new Map<string, AiResultView>();
let mockPrd: PrdView | null = null;
let mockPrdVersion: PrdVersionView | null = null;
let mockReview: DesignReviewView | null = null;
const initialMockPlan: ImplementationPlanView = { id: "plan-1", projectVersionId: "atlas-v2", sourcePrdVersionId: "prd-version-1", sourceDesignReviewId: "review-1", name: "Atlas 实现计划", status: "draft", currentVersionId: null, effectiveVersionId: null, rowVersion: 1, confirmationState: "not_ready", versions: [] };
const mockPlans = new Map<string, ImplementationPlanView>([[initialMockPlan.id, initialMockPlan]]);
const mockRoundsByPlan = new Map<string, import("./ports").ConfirmationRoundView[]>();
const getMockPlan = (planId: string) => mockPlans.get(planId);
const roundsFor = (planId: string) => { const existing = mockRoundsByPlan.get(planId); if (existing) return existing; const created: import("./ports").ConfirmationRoundView[] = []; mockRoundsByPlan.set(planId, created); return created; };
const readinessComplete = (readiness: import("./ports").ReadinessView) => readiness.scopeStatus === "ready" && readiness.implementationStatus === "ready" && ["ready", "not_applicable"].includes(readiness.configurationStatus) && ["ready", "not_applicable"].includes(readiness.dataChangeStatus) && readiness.knownBlockers.length === 0;

export const mockApi: FrontendApi = {
  identity: { async login(input) { await wait(); if (!input.email || !input.password || input.email.includes("fail")) throw new PortError("FAILED", "邮箱或密码不正确。"); return session; }, async register(input) { await wait(); if (!input.displayName || !input.email || input.password.length < 12) throw new PortError("FAILED", "请完整填写信息，密码至少 12 位。"); return session; }, async refresh() { await wait(); return session; }, async logout() { await wait(); } },
  projects: { async list(scenario) { await wait(); fail(scenario); return scenario === "empty" || scenario === "filtered-empty" ? [] : projects; }, async create(input: CreateProjectInput, scenario) { await wait(); fail(scenario); if (!input.name || !input.goal) throw new PortError("FAILED", "请填写项目名称与目标。"); return { projectId: "new-project", workingVersionId: "new-project-v1" }; }, async overview(projectId, viewedVersionId) { await wait(); return overview(projectId, viewedVersionId); }, async versions() { await wait(); return versions; }, async setWorking(projectId, versionId, _expected, scenario) { await wait(); fail(scenario); return { ...overview(projectId, versionId), workingVersionId: versionId, workingVersionNo: versions.find((v) => v.id === versionId)?.number ?? "V1", isHistory: false, canEdit: true }; }, async derive(_projectId, input: DeriveVersionInput, scenario) { await wait(); fail(scenario); if (!input.reason.trim()) throw new PortError("FAILED", "必须记录派生原因。"); return { id: "atlas-v3", number: "V3", source: input.sourceVersionId, reason: input.reason, createdAt: "2026-07-29T10:00:00Z", isWorking: false }; } },
  implementationPlans: {
    async list(projectVersionId) { await wait(); return [...mockPlans.values()].filter((plan) => plan.projectVersionId === projectVersionId).map((plan) => ({ ...plan, versions: [] })); },
    async create(projectVersionId, input: CreateImplementationPlanInput) { await wait(); if (!input.name.trim()) throw new PortError("FAILED", "请填写实现计划名称。", 422, undefined, [], "VALIDATION_ERROR"); const id = `plan-${mockPlans.size + 1}`; const plan: ImplementationPlanView = { id, projectVersionId, name: input.name, sourcePrdVersionId: input.sourcePrdVersionId, sourceDesignReviewId: input.sourceDesignReviewId, status: "draft", currentVersionId: null, effectiveVersionId: null, rowVersion: 1, confirmationState: "not_ready", versions: [] }; mockPlans.set(id, plan); return plan; },
    async get(planId) { await wait(); const plan = getMockPlan(planId); if (!plan) throw new PortError("FAILED", "实现计划不存在。", 404, undefined, [], "NOT_FOUND"); return { ...plan, versions: [...plan.versions] }; },
    async saveVersion(planId, input: SaveImplementationPlanVersionInput) { await wait(); const plan = getMockPlan(planId); if (!plan) throw new PortError("FAILED", "实现计划不存在。", 404, undefined, [], "NOT_FOUND"); if (input.expectedVersion !== plan.rowVersion) throw new PortError("CONFLICT", "实现计划已被更新，请重新读取。", 409, undefined, [], "VERSION_CONFLICT"); const version = { id: `${planId}-version-${plan.versions.length + 1}`, implementationPlanId: plan.id, sourceVersionId: plan.currentVersionId, versionNo: `V${plan.versions.length + 1}`, reviewId: plan.sourceDesignReviewId, content: input.content, contentHash: "p".repeat(64), changeNote: input.changeNote, isEffective: false, createdBy: session.user.id, createdAt: new Date().toISOString() }; const next = { ...plan, currentVersionId: version.id, rowVersion: plan.rowVersion + 1, versions: [...plan.versions, version] }; mockPlans.set(planId, next); return { version, planRowVersion: next.rowVersion }; },
    async setEffective(planVersionId, expectedVersion) { await wait(); const plan = [...mockPlans.values()].find((item) => item.currentVersionId === planVersionId); if (!plan) throw new PortError("CONFLICT", "只能激活当前版本。", 409, undefined, [], "PLAN_VERSION_NOT_CURRENT"); if (expectedVersion !== plan.rowVersion) throw new PortError("CONFLICT", "实现计划已被更新，请重新读取。", 409, undefined, [], "VERSION_CONFLICT"); const history = roundsFor(plan.id); const next = { ...plan, effectiveVersionId: planVersionId, rowVersion: plan.rowVersion + 1, status: "active" as const, confirmationState: history.some((round) => round.status === "confirmed" || round.status === "superseded") ? "needs_reconfirmation" as const : "needs_confirmation" as const, versions: plan.versions.map((version) => ({ ...version, isEffective: version.id === planVersionId })) }; history.forEach((round) => { round.isEffective = false; }); mockPlans.set(plan.id, next); return next; },
  },
  confirmationRounds: {
    async list(planId) { await wait(); return roundsFor(planId).map((round) => ({ ...round })); },
    async create(planId, input: CreateConfirmationRoundInput) { await wait(); const plan = getMockPlan(planId); if (!plan) throw new PortError("FAILED", "实现计划不存在。", 404, undefined, [], "NOT_FOUND"); const rounds = roundsFor(planId); if (rounds.some((round) => round.status === "draft")) throw new PortError("CONFLICT", "已有待确认草稿。", 409, undefined, [], "CONFIRMATION_ALREADY_EXISTS"); const history = rounds.filter((round) => round.status === "confirmed" || round.status === "superseded"); const prior = history.at(-1); const round = { id: `${planId}-round-${rounds.length + 1}`, implementationPlanId: planId, planVersionId: input.planVersionId, sourceRoundId: prior?.id ?? null, roundNo: rounds.reduce((max, item) => Math.max(max, item.roundNo), 0) + 1, status: "draft" as const, confirmStatus: null, implementationSummary: input.implementationSummary, readiness: input.readiness, rowVersion: 1, isEffective: false, confirmedBy: null, confirmedAt: null, supersededAt: null }; rounds.push(round); return round; },
    async get(roundId) { await wait(); const round = [...mockRoundsByPlan.values()].flat().find((item) => item.id === roundId); if (!round) throw new PortError("FAILED", "确认轮次不存在。", 404, undefined, [], "NOT_FOUND"); return { ...round }; },
    async updateDraft(roundId, input: UpdateConfirmationRoundDraftInput) { await wait(); const round = [...mockRoundsByPlan.values()].flat().find((item) => item.id === roundId); if (!round) throw new PortError("FAILED", "确认轮次不存在。", 404, undefined, [], "NOT_FOUND"); if (round.status !== "draft") throw new PortError("CONFLICT", "确认历史不可修改。", 409, undefined, [], "CONFIRMATION_NOT_DRAFT"); if (round.rowVersion !== input.expectedVersion) throw new PortError("CONFLICT", "确认轮次已被更新，请重新读取。", 409, undefined, [], "VERSION_CONFLICT"); Object.assign(round, { planVersionId: input.planVersionId, implementationSummary: input.implementationSummary, readiness: input.readiness, rowVersion: round.rowVersion + 1 }); return { ...round }; },
    async confirm(roundId, expectedVersion) { await wait(); const pair = [...mockRoundsByPlan.entries()].flatMap(([planId, rounds]) => rounds.map((round) => [planId, round] as const)).find(([, round]) => round.id === roundId); const round = pair?.[1]; if (!round) throw new PortError("FAILED", "确认轮次不存在。", 404, undefined, [], "NOT_FOUND"); if (round.status !== "draft") throw new PortError("CONFLICT", "确认历史不可修改。", 409, undefined, [], "CONFIRMATION_NOT_DRAFT"); if (round.rowVersion !== expectedVersion) throw new PortError("CONFLICT", "确认轮次已被更新，请重新读取。", 409, undefined, [], "VERSION_CONFLICT"); if (!readinessComplete(round.readiness)) throw new PortError("CONFLICT", "Readiness 尚未完成。", 409, undefined, [], "READINESS_INCOMPLETE"); const rounds = mockRoundsByPlan.get(pair[0])!; const previous = rounds.filter((item) => item.id !== round.id && (item.status === "confirmed" || item.status === "superseded")).sort((a, b) => b.roundNo - a.roundNo)[0]; if (previous) Object.assign(previous, { status: "superseded", isEffective: false, supersededAt: new Date().toISOString() }); Object.assign(round, { status: "confirmed", confirmStatus: "confirmed", isEffective: true, confirmedBy: session.user.id, confirmedAt: new Date().toISOString(), rowVersion: round.rowVersion + 1 }); const plan = getMockPlan(pair[0]); if (plan) mockPlans.set(pair[0], { ...plan, confirmationState: "confirmed" }); return { ...round }; },
  },
  requirements: {
    async list() { await wait(); return [mockRequirement.requirement]; },
    async get() { await wait(); return mockRequirement; },
    async create(_versionId, input) { await wait(); if (!input.title.trim() || !input.rawInput.trim()) throw new PortError("FAILED", "请填写需求标题与内容。"); mockRequirement = { ...mockRequirement, requirement: { ...mockRequirement.requirement, title: input.title }, currentVersion: { ...mockRequirement.currentVersion!, content: { ...content("auto", input.rawInput), rawInputRef: input.sourceRefs?.[0] ?? sourceRef } } }; return mockRequirement; },
    async setClarificationMode(_versionId, input) { await wait(); if (input.mode === "deep" && !input.reason?.trim()) throw new PortError("FAILED", "深度模式需要说明原因。"); const version = { ...mockRequirement.currentVersion!, content: { ...mockRequirement.currentVersion!.content, clarification: { ...mockRequirement.currentVersion!.content.clarification, mode: input.mode } } }; mockRequirement = { ...mockRequirement, currentVersion: version }; return version; },
    async submitClarificationAnswers(_versionId, input) { await wait(); const version = mockRequirement.currentVersion!; const round = { roundNo: input.roundNo, aiTaskId: `mock-task-${input.roundNo}`, aiResultId: `mock-result-${input.roundNo}`, questions: [], answers: input.answers }; const next = { ...version, content: { ...version.content, clarification: { ...version.content.clarification, rounds: [...version.content.clarification.rounds, round], finishReason: input.finishNow ? "user_finished" as const : null } } }; mockRequirement = { ...mockRequirement, currentVersion: next }; return { version: next, baselineCandidateRef: null }; },
    async revise(_versionId, input) { await wait(); const version = { ...mockRequirement.currentVersion!, content: input.content ?? mockRequirement.currentVersion!.content, riskAcceptances: input.riskAcceptances ?? mockRequirement.currentVersion!.riskAcceptances, versionNo: "V2", id: "req-v2", unresolvedCount: (input.content ?? mockRequirement.currentVersion!.content).baseline.unresolvedItems.length }; mockRequirement = { ...mockRequirement, currentVersion: version }; return version; },
    async confirm(_versionId, input) { await wait(); if ((mockRequirement.currentVersion?.content.baseline.unresolvedItems.length ?? 0) > 0 && !(input.riskAcceptances?.length)) throw new PortError("CONFLICT", "仍有未解决阻断项，请先处理或接受风险。"); const version = { ...mockRequirement.currentVersion!, confirmationStatus: "confirmed" as const, isEffective: true, riskAcceptances: input.riskAcceptances ?? [] }; mockRequirement = { ...mockRequirement, currentVersion: version, effectiveVersion: version, requirement: { ...mockRequirement.requirement, status: "effective", effectiveVersionId: version.id } }; return { version, gateResult: input.riskAcceptances?.length ? "passed_with_risk" as const : "passed" as const }; },
  },
  prds: {
    async list() { await wait(); return mockPrd ? [mockPrd] : []; },
    async create(projectVersionId: string, input: CreatePrdInput) { await wait(); if (!input.name.trim() || !input.sourceRequirementVersionId) throw new PortError("FAILED", "必须提供 PRD 名称和已确认 Requirement Version。"); mockPrd = { id: "mock-prd-1", projectVersionId, sourceRequirementVersionId: input.sourceRequirementVersionId, name: input.name, status: "draft", rowVersion: 1, currentVersionId: null }; return mockPrd; },
    async get() { await wait(); if (!mockPrd) throw new PortError("FAILED", "PRD 不存在。"); return mockPrd; },
    async getVersion() { await wait(); if (!mockPrdVersion) throw new PortError("FAILED", "PRD Version 不存在。"); return mockPrdVersion; },
    async saveVersion(_prdId: string, input: SavePrdVersionInput) { await wait(); if (!mockPrd) throw new PortError("FAILED", "PRD 不存在。"); if (mockPrd.rowVersion !== input.expectedVersion) throw new PortError("CONFLICT", "PRD 已被更新，请重新读取。", 409, undefined, [], "VERSION_CONFLICT"); const versionNo = `V${mockPrdVersion ? Number(mockPrdVersion.versionNo.slice(1)) + 1 : 1}`; mockPrdVersion = { id: `mock-prd-version-${versionNo}`, prdId: mockPrd.id, versionNo, contentHash: "p".repeat(64), content: input.content, sourceVersionId: mockPrd.currentVersionId, isEffective: true }; mockPrd = { ...mockPrd, currentVersionId: mockPrdVersion.id, rowVersion: mockPrd.rowVersion + 1, status: "draft" }; return mockPrdVersion; },
    async submitReview(_projectVersionId: string, input: SubmitPrdReviewInput) { await wait(); if (!mockPrd || !mockPrdVersion) throw new PortError("FAILED", "请先保存 PRD Version。"); if (mockPrd.rowVersion !== input.expectedVersion) throw new PortError("CONFLICT", "PRD 已被更新，请重新读取。", 409, undefined, [], "VERSION_CONFLICT"); mockPrd = { ...mockPrd, status: "in_review", rowVersion: mockPrd.rowVersion + 1 }; mockReview = { id: `mock-review-${(mockReview?.roundNo ?? 0) + 1}`, projectVersionId: mockPrd.projectVersionId, roundNo: (mockReview?.roundNo ?? 0) + 1, rowVersion: 1, status: "open", summary: null, prdId: mockPrd.id, prdVersionId: mockPrdVersion.id, contentHash: mockPrdVersion.contentHash }; return mockReview; },
    async getReview() { await wait(); if (!mockReview) throw new PortError("FAILED", "Design Review 不存在。"); return mockReview; },
    async decideReview(_reviewId: string, input: DecidePrdReviewInput) { await wait(); if (!mockReview || !mockPrd) throw new PortError("FAILED", "Design Review 不存在。"); if (mockReview.rowVersion !== input.expectedVersion) throw new PortError("CONFLICT", "Review 已被更新，请重新读取。", 409, undefined, [], "VERSION_CONFLICT"); if (input.decision === "changes_requested" && !input.summary?.trim()) throw new PortError("FAILED", "changes_requested 必须填写 summary。", 422, undefined, [], "VALIDATION_ERROR"); mockReview = { ...mockReview, status: input.decision === "pass" ? "passed" : "changes_requested", summary: input.decision === "pass" ? null : input.summary!.trim(), rowVersion: mockReview.rowVersion + 1 }; mockPrd = { ...mockPrd, status: input.decision === "pass" ? "confirmed" : "changes_requested", rowVersion: mockPrd.rowVersion + 1 }; return mockReview; },
  },
  ai: {
    async createTask(input) { await wait(); const taskId = `mock-task-${++taskCounter}`; const status = input.userInstruction === "simulate_failure" ? "failed" as const : "ready" as const; const targetSnapshotHash = "2".repeat(64); const resultId = `mock-result-${taskId}`; const task: AiTaskView = { taskId, taskPublicId: taskId, taskType: "requirement.clarify", status, targetSnapshotHash, pollUrl: `/mock/tasks/${taskId}`, eventsUrl: `/mock/tasks/${taskId}/events`, missingItems: [], createdByUserId: session.user.id, queuedAt: new Date().toISOString(), resultRefs: status === "ready" ? [{ resultId, status: "ready", targetSnapshotHash }] : [] }; mockTasks.set(taskId, task); const mode = mockRequirement.currentVersion?.content.clarification.mode ?? "auto"; const baseline = emptyBaseline(); baseline.dimensions.goal.confirmedFacts = [mockRequirement.currentVersion?.content.rawInput ?? "人工输入"]; baseline.dimensions.goal.sourceRefs = [sourceRef]; const resultKind = mode === "auto" ? "assessment" as const : mode === "skip" ? "baseline" as const : "questions" as const; const result: AiResultView = { id: resultId, taskPublicId: taskId, taskType: "requirement.clarify", targetSnapshotHash: task.targetSnapshotHash, mode, roundNo: resultKind === "assessment" ? 0 : 1, resultKind, status: task.status === "failed" ? "failed" : "ready", content: task.status === "failed" ? null : { assessment: resultKind === "assessment" ? mockAssessment() : null, questions: resultKind === "questions" ? [{ questionId: "q-goal", dimension: "goal", questionText: "要解决的核心问题是什么？", reason: "补充目标与验收依据", sourceRefs: [sourceRef] }] : [], baseline: resultKind === "baseline" ? baseline : null }, convergence: { shouldFinish: resultKind === "baseline", finishReason: resultKind === "baseline" ? "mode_skipped" : null, nextRoundNo: resultKind === "baseline" ? null : 1 }, quality: { formatStatus: "passed", traceabilityStatus: "passed", safetyStatus: "passed", requiredItemsMet: resultKind === "baseline" ? 8 : 6, requiredItemsTotal: 8, majorError: false, blockerCodes: [] }, capabilitySummary: { truthLabel: "FORMAL_MOCK", providerCode: "formal_mock", modelCode: null } }; mockResults.set(result.id, result); mockResults.set(taskId, result); return task; },
    async getTask(taskId) { await wait(); const task = mockTasks.get(taskId); if (!task) throw new PortError("FAILED", "任务不存在。"); return task; },
    async getResult(resultId) { await wait(); const result = mockResults.get(resultId); if (!result) throw new PortError("FAILED", "结果尚未就绪。"); return result; },
    async formalizeBaseline(resultId, input) { await wait(); const result = mockResults.get(resultId); if (!result || result.resultKind !== "baseline" || !result.content?.baseline || result.status !== "ready") throw new PortError("FAILED", "只有合格的 Baseline 候选可以正式采用。"); const previous = mockRequirement.currentVersion!; const versionNo = `V${input.expectedVersion + 1}`; const version = { ...previous, id: `req-v${input.expectedVersion + 1}`, versionNo, contentHash: result.targetSnapshotHash, content: { ...previous.content, baseline: result.content.baseline }, createdFromAiResultId: result.id, confirmationStatus: "confirmed" as const, isEffective: true }; mockRequirement = { ...mockRequirement, requirement: { ...mockRequirement.requirement, status: "effective", version: input.expectedVersion + 1, currentVersionId: version.id, effectiveVersionId: version.id }, currentVersion: version, effectiveVersion: version }; return { id: version.id, versionNo, status: "confirmed", contentHash: version.contentHash, createdAt: new Date().toISOString() }; },
  },
  files: { async list() { await wait(); return []; }, async upload(_projectId, file, scenario) { await wait(); if (scenario === "failure") return { id: `failed-${file.name}`, name: file.name, progress: 62, status: "failed", relation: null, error: "存储暂不可用，文件尚未完成入库。" }; return { id: `file-${file.name}`, name: file.name, progress: 100, status: "uploaded", relation: null }; }, async retry(_projectId, item) { await wait(); return { ...item, progress: 100, status: "uploaded", error: undefined }; }, async relate(_projectId, fileId, relation) { await wait(); return { id: fileId, name: fileId.replace(/^file-/, ""), progress: 100, status: "uploaded", relation }; } },
  health: { async get() { await wait(); return { status: "healthy", service: "mock-api", environment: "local", release: "mock", traceId: "mock-trace" }; } },
};
